task:
  labels:
  - Q1
  - Q2
  - Q3
  - Q4
  cls_type: AV
  n_class: 4
wav:
  feature_path: ../dataset/resample22050
  input_length: 3
  sr: 22050
monitor:
  metric: val_acc
  mode: max
hparams:
  dataset: EMOPIA
  task: ar_va
  wav: sr22k
  monitor: acc
  patience: 5
  n_channels: 128
  n_fft: 1024
  n_mels: 128
  f_min: 0
  f_max: 11025
  batch_size: 128
  num_workers: 4
  lr: 0.0001
  weight_decay: 0.0001
  T_0: 16
  max_epochs: 100
  gpus: 1
  distributed_backend: dp
  deterministic: true
  benchmark: false
  reproduce: true
