task:
  labels:
  - HA
  - LA
  cls_type: A
  num_of_dim: 2
midi:
  feature_path: ./dataset/magenta_midi
  pad_idx: 388
hparams:
  dataset: EMOPIA
  midi: magenta
  task: arousal
  r: 16
  lstm_hidden_dim: 128
  embedding_size: 300
  batch_size: 32
  num_workers: 8
  lr: 0.005
  weight_decay: 0.0001
  T_0: 5
  max_epochs: 400
  gpus: 1
  distributed_backend: dp
  deterministic: true
  benchmark: false
  reproduce: true
