task:
  labels:
  - HA
  - LA
  cls_type: A
  num_of_dim: 2
midi:
  feature_path: ./dataset/remi_midi_test1
  pad_idx: 338
hparams:
  dataset: EMOPIA
  midi: remi
  task: arousal
  r: 8
  lstm_hidden_dim: 128
  embedding_size: 300
  batch_size: 8
  num_workers: 6
  lr: 0.005
  weight_decay: 0.0001
  T_0: 5
  max_epochs: 400
  gpus: 1
  distributed_backend: dp
  deterministic: true
  benchmark: false
  reproduce: true
